default:
  image: python:3.13
  cache:
    paths:
      - .pip_cache
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install poetry==2.1.2
    - poetry install --only=dev --no-interaction
    - poetry install --no-root --no-interaction
    - eval $(poetry env activate)

stages:
  - check
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

isort:
  stage: check
  script:
    - isort .

flake8:
  stage: check
  script:
    - flake8 .

mypy:
  stage: check
  script:
    - mypy .

pylint:
  stage: check
  script:
    - pylint .

# TODO
# docker:
#   stage: test
#   image: docker:28.0.1
#   services:
#     - docker:28.0.1-dind
#   before_script:
#     - apk update
#     - apk add bash
#   script:
#     - ls -al
#     - pwd
#     - ./build.sh
#     - ./emfuzzer.sh --help

pytest:
  stage: test
  script:
    - pytest
