default:
  image: python:3.13
  cache:
    paths:
      - .pip_cache
  before_script:
    - python --version ; pip --version  # For debugging
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements-dev.txt

stages:
  - check
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

isort:
  stage: check
  script:
    - isort --profile black .

flake8:
  stage: check
  script:
    - flake8 .

mypy:
  stage: check
  script:
    - mypy .

docker:
  stage: test
  image: docker:28.0.1
  services:
    - docker:28.0.1-dind
  before_script: []
  script:
    - ls -al
    - pwd
    - ./build.sh
    - ./coapper.sh --help

pytest:
  stage: test
  script:
    - python -m pytest
