# TODO
# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"

[project]
name = "emfuzzer"
# TODO description
dynamic = ["version"]  # TODO
# TODO dependencies
requires-python = ">= 3.13"
# TODO authors
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]

# TODO [project.urls]

# TODO [project.scripts]

# TODO [project.entry-points.

[tool.mypy]
strict = true

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 100

[tool.flake8]
max-line-length = 100
exclude = [
  "__pycache__",
  ".venv",
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"

[tool.pylint.main]
ignore = [
  "__pycache__",
  ".venv",
  ".git",
]
jobs = 0

[tool.pylint.format]
max-line-length = 100

[tool.pylint.logging]
logging-format-style = "new"

[tool.pylint."messages control"]
disable = [
  "missing-function-docstring",
  "missing-module-docstring", # TODO
  "missing-class-docstring", # TODO ?
  "logging-fstring-interpolation",
#  "raw-checker-failed",
  #"bad-inline-option",
  #"locally-disabled",
  #"file-ignored",
  #"suppressed-message",
  #"useless-suppression",
  #"deprecated-pragma",
  #"use-symbolic-message-instead",
  #"use-implicit-booleaness-not-comparison-to-string",
  #"use-implicit-booleaness-not-comparison-to-zero",
]
enable = [
  "useless-suppression",
]

[tool.pylint.similarities]
# TODO
min-similarity-lines = 5

[tool.pylint.imports]
allow-reexport-from-package = true
